version: '3.10'

services:
  django:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    
  db:
    image: postgres
    restart: always
    env_file:
      - postgres.env
    ports:
      - "54325:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"