# Generated by Django 4.2.5 on 2023-09-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_follow_profile_photo_alter_profile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
